LLM_BACKEND = "gemini"
GEMINI_API_KEY = "AIzaSyCJaQgiTPN0h9V1tsRXBHkhLgX-iEpb0GM"
GEMINI_MODEL = "gemini-1.5-flash"
LLM_BACKEND = "gemini"
GEMINI_API_KEY = "AIzaSyCJaQgiTPN0h9V1tsRXBHkhLgX-iEpb0GM"
GEMINI_MODEL = "gemini-1.5-flash"
