LLM_BACKEND = "gemini"
GEMINI_API_KEY = "AIzaSyAGLdSG-C6xJ8cWXHlpyXMPKir_JpxGmTw"
GEMINI_MODEL = "gemini-1.5-flash"
LLM_BACKEND = "gemini"
GEMINI_API_KEY = "AIzaSyAGLdSG-C6xJ8cWXHlpyXMPKir_JpxGmTw"
GEMINI_MODEL = "gemini-1.5-flash"
