LLM_BACKEND = "gemini"
GEMINI_API_KEY = "AIzaSyCVoFXzRPhAPnSperqHsWmj7f3W-vbc2Zc"
GEMINI_MODEL = "gemini-1.5-flash"
LLM_BACKEND = "gemini"
GEMINI_API_KEY = "AIzaSyCVoFXzRPhAPnSperqHsWmj7f3W-vbc2Zc"
GEMINI_MODEL = "gemini-1.5-flash"
